<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6967a7194079d',
    'title' => __('Noticeboard: Module settings', 'modularity-toc'),
    'fields' => array(
        0 => array(
            'key' => 'field_6972396dc1287',
            'label' => __('Display as', 'modularity-toc'),
            'name' => 'display_as',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'card' => __('Card', 'modularity-toc'),
                'news' => __('News', 'modularity-toc'),
            ),
            'default_value' => 'card',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 1,
            'ajax' => 0,
            'create_options' => 0,
            'save_options' => 0,
        ),
        1 => array(
            'key' => 'field_696dd85a5f878',
            'label' => __('Archive mode', 'modularity-toc'),
            'name' => 'archive_mode',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Will display all notices that are published', 'modularity-toc'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        2 => array(
            'key' => 'field_696f68e1fa2cc',
            'label' => __('Specific types', 'modularity-toc'),
            'name' => 'specific_types',
            'aria-label' => '',
            'type' => 'acfe_taxonomy_terms',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_696dd85a5f878',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => array(
                0 => 'noticeboard_notice_type',
            ),
            'allow_terms' => '',
            'allow_level' => '',
            'field_type' => 'select',
            'default_value' => array(
            ),
            'return_format' => 'id',
            'ui' => 1,
            'allow_null' => 1,
            'placeholder' => '',
            'multiple' => 1,
            'ajax' => 0,
            'save_terms' => 0,
            'load_terms' => 0,
            'allow_in_bindings' => 0,
            'choices' => array(
            ),
            'search_placeholder' => '',
            'layout' => '',
            'toggle' => 0,
            'allow_custom' => 0,
            'other_choice' => 0,
        ),
        3 => array(
            'key' => 'field_6967a7191f762',
            'label' => __('Group by notice type', 'modularity-toc'),
            'name' => 'group_by_notice_type',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        4 => array(
            'key' => 'field_696dd87a5f879',
            'label' => __('Notices to show', 'modularity-toc'),
            'name' => 'notices_to_show',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_696dd85a5f878',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 5,
            'min' => 1,
            'max' => 20,
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'step' => 1,
            'prepend' => '',
            'append' => '',
        ),
        5 => array(
            'key' => 'field_69720fd4c8873',
            'label' => __('Show link to main page', 'modularity-toc'),
            'name' => 'archive_button',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Adds a button that links to the main page set in settings', 'modularity-toc'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_696dd85a5f878',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-noticeboard',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/noticeboard',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}