<?php

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_69720e679fc2b',
        'title' => __('Noticeboard settings', 'modularity-noticeboard'),
        'fields' => array(
            0 => array(
                'key' => 'field_697a06c6be319',
                'label' => __('Post type name', 'modularity-noticeboard'),
                'name' => 'post_type_slug',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => __('If you want a particular name for the notice post type, for instance notis, you can replace this value. Don\'t forget to save permalinks after changing this.', 'modularity-noticeboard'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => __('notice', 'modularity-noticeboard'),
                'prepend' => '',
                'append' => '',
            ),
            1 => array(
                'key' => 'field_69720e67a61d4',
                'label' => __('Noticeboard context page', 'modularity-noticeboard'),
                'name' => 'noticeboard_main_page',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => __('Optional if the same page is already set as the noticeboard archive under Reading (page for this post type). Otherwise pick the page whose title and ancestors should appear in breadcrumbs. Singles use the post type archive URL for the last crumb when it exists.', 'modularity-noticeboard'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'page',
                ),
                'post_status' => array(
                    0 => 'publish',
                ),
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'allow_null' => 1,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(
                ),
                'save_post_type' => '',
            ),
            2 => array(
                'key' => 'field_697a69b88e075',
                'label' => __('Archival action', 'modularity-noticeboard'),
                'name' => 'archival_action',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => __('When a notice is archived, what will happen to it?', 'modularity-noticeboard'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'unpublish' => __('Unpublish', 'modularity-noticeboard'),
                    'delete' => __('Delete', 'modularity-noticeboard'),
                ),
                'default_value' => 'unpublish',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'create_options' => 0,
                'save_options' => 0,
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
        ),
        'location' => array(
            0 => array(
                0 => array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'display_title' => '',
        'acfe_autosync' => array(
            0 => 'json',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
}
